"""Add fields to Check Request model

Revision ID: ea55190672a2
Revises: 6cb509aef774
Create Date: 2024-11-22 15:02:05.988379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea55190672a2'
down_revision = '6cb509aef774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.Text(), nullable=True))
        batch_op.alter_column('input',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('words_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_request', schema=None) as batch_op:
        batch_op.alter_column('words_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('input',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
