"""Create Chech Request Table

Revision ID: 05f4d77a9c3c
Revises: e2e82b287ea7
Create Date: 2024-11-19 20:08:30.749318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f4d77a9c3c'
down_revision = 'e2e82b287ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_group_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_group_id', sa.Integer(), nullable=False),
    sa.Column('external_user_id', sa.BigInteger(), nullable=False),
    sa.Column('external_username', sa.String(length=50), nullable=True),
    sa.Column('sus_counter', sa.Integer(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_group_id'], ['telegram_group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('is_sus', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_group_member_id', sa.Integer(), nullable=True),
    sa.Column('check_time', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('words_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_group_member_id'], ['telegram_group_member.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_request')
    op.drop_table('telegram_group_member')
    # ### end Alembic commands ###
