"""Create Sus Error Table

Revision ID: 30e97200e831
Revises: 422aab155264
Create Date: 2024-11-19 20:10:38.636830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e97200e831'
down_revision = '422aab155264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sus_error',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_request_id', sa.Integer(), nullable=False),
    sa.Column('actual_sus', sa.Boolean(), nullable=False),
    sa.Column('is_game', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['check_request_id'], ['check_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sus_error')
    # ### end Alembic commands ###
