"""Changed game table mandatory fields

Revision ID: 3697b13624b2
Revises: e5c2b836be95
Create Date: 2024-11-24 01:44:36.102511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3697b13624b2'
down_revision = 'e5c2b836be95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('user_score',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('user_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
