"""Create Feedback Table

Revision ID: 422aab155264
Revises: 05f4d77a9c3c
Create Date: 2024-11-19 20:10:07.235364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422aab155264'
down_revision = '05f4d77a9c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_request_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('actual_sus', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='check_feedback_rating'),
    sa.ForeignKeyConstraint(['check_request_id'], ['check_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
