"""Create Telegram Group Table

Revision ID: 6446f315ddf9
Revises: 8185bccaabc1
Create Date: 2024-11-19 20:03:27.406753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6446f315ddf9'
down_revision = '8185bccaabc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_group_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_enabled', sa.Boolean(), nullable=False),
    sa.Column('ban_enabled', sa.Boolean(), nullable=False),
    sa.Column('mute_enabled', sa.Boolean(), nullable=False),
    sa.Column('ban_threshold', sa.Integer(), nullable=True),
    sa.Column('mute_threshold', sa.Integer(), nullable=True),
    sa.Column('sus_min_confidence', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('spam_min_confidence', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.drop_table('telegram_group')
    # ### end Alembic commands ###
