"""Create Game Check Request Table

Revision ID: 6cb509aef774
Revises: 2b19a89bbfde
Create Date: 2024-11-19 20:12:02.232592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb509aef774'
down_revision = '2b19a89bbfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_check_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('check_request_id', sa.Integer(), nullable=False),
    sa.Column('ai_sus', sa.Boolean(), nullable=True),
    sa.Column('user_sus', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['check_request_id'], ['check_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_check_request')
    # ### end Alembic commands ###
