"""Changed check request numeric values

Revision ID: c3b417a163fa
Revises: ea55190672a2
Create Date: 2024-11-22 16:47:41.711708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b417a163fa'
down_revision = 'ea55190672a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_request', schema=None) as batch_op:
        batch_op.alter_column('confidence',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=False)
        batch_op.alter_column('check_time',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_request', schema=None) as batch_op:
        batch_op.alter_column('check_time',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
        batch_op.alter_column('confidence',
               existing_type=sa.Numeric(precision=10, scale=9),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
